### ISSUE TITLE
InitializeEnv.bat script fails compilation due to MFC not installed?

### ISSUE THREAD

**Issue by oscarbg** [fstudio/clangbuilder#17]
running  .\script\InitializeEnv.bat fails:
\clangbuilder-master\tools\clangbuilderui\MainWindow.h(9): fatal error C1083: No se puede abrir e archivo incluir: 'atlbase.h': No such file or directory
I have no MFC Visual Studio 2017 installed.. it's needed?
can you remove dependency?
thanks..

**Comment by fcharlie** [comment]
You should install ATL Component, https://github.com/fstudio/clangbuilder/blob/9ee5dfd759ada260632dd368b7b4263df321289e/tools/ClangbuilderUI/MainWindow.h#L48

ClangbuilderUI use **ATL** Window Template class. so you should modify you Visual Studio 2017. 
MFC not need。

**Comment by fcharlie** [comment]
You can click `UpdatePkgs.bat` after run `clangbuilder.bat`, Argument:

```powershell
param (
    [ValidateSet("x86", "x64", "ARM", "ARM64")]
    [String]$Arch = "x64",
    [ValidateSet("Release", "Debug", "MinSizeRel", "RelWithDebug")]
    [String]$Flavor = "Release",
    [ValidateSet("MSBuild", "Ninja", "NinjaBootstrap", "NinjaIterate")]
    [String]$Engine = "MSBuild",
    [ValidateSet("Mainline", "Stable", "Release")]
    [String]$Branch = "Mainline", #mainline 
    [String]$InstanceId, # install id
    [String]$InstallationVersion, # installationVersion
    [Switch]$Environment, # start environment 
    [Switch]$Sdklow, # low sdk support
    [Switch]$LLDB,
    [Switch]$Static,
    [Switch]$Package,
    [Switch]$ClearEnv
)
```

Check InstanceId and InstallationVersion, Please run vswhere.

**Comment by fcharlie** [comment]
![image](https://user-images.githubusercontent.com/6904176/30026768-f19fe3be-91b0-11e7-8990-87ff68df3ec5.png)

**Comment by fcharlie** [comment]
Now You can download this x64 ClangbuilderUI.exe。 and unpack to clangbuilder' root directory. run `UpdatePkgs.bat` .after click ClangbuilderUI.exe

[ClangbuilderUI.Win64.zip](https://github.com/fstudio/clangbuilder/files/1274689/ClangbuilderUI.Win64.zip)

**Comment by oscarbg** [comment]
Many thanks!
