### ISSUE TITLE
End of Central Directory record could not be found - and other errors

### ISSUE THREAD

**Issue by Bluesman74** [fstudio/clangbuilder#18]
Hi, I tried your bootstrap batch file (script/InitializeEnv.bat) and get the following errors

Install new GNUWin: 1.0 ...
Download http://downloads.sourceforge.net/projects/clangonwin/files/Install/Packages/ClangSetup-Package-GnuWin-win32.zip ...
New-Object : Exception calling ".ctor" with "3" argument(s): "End of Central Directory record could not be found."
At
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:933
char:23
+ ... ipArchive = New-Object -TypeName System.IO.Compression.ZipArchive -Ar ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand

Install new Ninja: 1.7.2 ...
Download https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-win.zip ...
Install new swigwin: 3.0.11 ...
Download https://downloads.sourceforge.net/project/swig/swigwin/swigwin-3.0.11/swigwin-3.0.11.zip ...
Install new vswhere: 2.1.3 ...
Download https://github.com/Microsoft/vswhere/releases/download/2.1.3/vswhere.exe ...

    Directory: E:\Documents\Programming\Code\Libraries\clangbuilder\pkgs

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       11/09/2017     19:56                vswhere
Copy-Item : Cannot bind argument to parameter 'Path' because it is null.
At E:\Documents\Programming\Code\Libraries\clangbuilder\modules\PM\PM.psm1:198 char:29
+             Copy-Item -Path $File -Destination $NewDir -Force
+                             ~~~~~
    + CategoryInfo          : InvalidData: (:) [Copy-Item], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CopyItemCommand

Install new NuGet: 4.3.0 ...
Download https://dist.nuget.org/win-x86-commandline/v4.3.0/nuget.exe ...
d-----       11/09/2017     19:57                NuGet
Copy-Item : Cannot bind argument to parameter 'Path' because it is null.
At E:\Documents\Programming\Code\Libraries\clangbuilder\modules\PM\PM.psm1:198 char:29
+             Copy-Item -Path $File -Destination $NewDir -Force
+                             ~~~~~
    + CategoryInfo          : InvalidData: (:) [Copy-Item], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CopyItemCommand

Update package completed.

DefaultVisualStudio : Invalid JSON primitive: Visual.
At E:\Documents\Programming\Code\Libraries\clangbuilder\bin\CompileUtils.ps1:9 char:1
+ DefaultVisualStudio -ClangbuilderRoot $ClangbuilderRoot # initialize  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DefaultVisualStudio

E:\Documents\Programming\Code\Libraries\clangbuilder>get

**Comment by fcharlie** [comment]
We update GNUWin to Gnuutils and Change URL to https, HTTP fuck of. EXE type package install failed, fix it.
Please try again.
