### ISSUE TITLE
Errors produced by script/VisualCppToolsFetch.bat

### ISSUE THREAD

**Issue by Bluesman74** [fstudio/clangbuilder#19]
When I run the script it produces the following errors:

Installing VisualCppTools.Community.Daily.D14Layout 14.11.25617-Pre.
Adding package 'VisualCppTools.Community.Daily.D14Layout.14.11.25617-Pre' to folder 'E:\Documents\Programming\Code\Libraries\clangbuilder\utils\msvc'
Added package 'VisualCppTools.Community.Daily.D14Layout.14.11.25617-Pre' to folder 'E:\Documents\Programming\Code\Libraries\clangbuilder\utils\msvc'
Successfully installed 'VisualCppTools.Community.Daily.D14Layout 14.11.25617-Pre' to E:\Documents\Programming\Code\Libraries\clangbuilder\utils\msvc
Executing nuget actions took 30.56 min
Out-File : A parameter cannot be found that matches parameter name 'Path'.
At E:\Documents\Programming\Code\Libraries\clangbuilder\bin\DownloadDailyCompiler.ps1:85 char:95
+ ... isualCppToolsVersion"|Out-File -Encoding unicode -Force -Path "$Visua ...
+                                                             ~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Out-File], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.OutFileCommand

**Comment by fcharlie** [comment]
Fix it, thanks,
