### ISSUE TITLE
libc++

### ISSUE THREAD

**Issue by d3roch4** [fstudio/clangbuilder#2]
Helo
You could add in build the libc++!

**Comment by fcharlie** [comment]
I'm sorry, libc++ does not currently support the Windows platform, so I waited.

**Comment by d3roch4** [comment]
And MinGW?

2016-02-22 10:42 GMT-03:00 Force.Charlie-I <notifications@github.com>:

**Comment by fcharlie** [comment]
MSYS2 can build libc++ https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-libc%2B%2B

**Comment by fcharlie** [comment]
@d3roch4 In Microsoft Visual C++ STL Team efforts, libc++ will support Visual C++ and clang-cl,
Your can goto https://twitter.com/StephanTLavavej ,

**Comment by fcharlie** [comment]
@d3roch4 Your can install LLVM on Windows, after checkout libcxx, build
```
mkdir out
cd out
cmake -G "Visual Studio 14 2015 Win64" -T "LLVM-vs2014" ..
```

but some test faild

**Comment by fcharlie** [comment]
See http://libcxx.llvm.org/docs/BuildingLibcxx.html#experimental-support-for-windows

**Comment by fcharlie** [comment]
```
 cmake -GNinja -DCMAKE_MAKE_PROGRAM=ninja -DCMAKE_C_COMPILER=../ninja/bin/clang-cl  -DC
MAKE_C_FLAGS="-fms-compatibility-version=19.00 --target=x86_64--windows"  -DCMAKE_CXX_COMPILER=../ninja/bin/clang-cl -DC
MAKE_CXX_FLAGS="-fms-compatibility-version=19.00 --target=x86_64--windows" -DLLVM_PATH=../mainline -DLIBCXX_ENABLE_SHARE
D=YES  -DLIBCXX_ENABLE_STATIC=NO  -DLIBCXX_ENABLE_EXPERIMENTAL_LIBRARY=NO ../libcxx
```

**Comment by fcharlie** [comment]
Clangbuilder Bootstrap (Build Engine NinjaBootstrap) support build libcxx

![image](https://user-images.githubusercontent.com/6904176/27983838-df6ce6fa-63f8-11e7-9e56-eabecb521e9f.png)
