### ISSUE TITLE
Clang Builder fails on Directories with spaces

### ISSUE THREAD

**Issue by Bluesman74** [fstudio/clangbuilder#20]
Happened to place your tool under the default "Visual Studio 2017" location, but when I hit building the Powershell script didn't understand the path

I got round it by creating a VS2017 junction into "Visual Studio 2017"

**Comment by fcharlie** [comment]
We use **vswhere** find `Visual Studio` Install location

Please check `pkgs/vswhere/vswhere.exe` is exists, after run 

```shell
vswhere  -prerelease -legacy -format json
```

Output like: 

```json
[
  {
    "instanceId": "432d6077",
    "installDate": "2017-06-25T13:11:37Z",
    "installationName": "VisualStudio/15.3.3+26730.12",
    "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community",
    "installationVersion": "15.3.26730.12",
    "isPrerelease": false,
    "displayName": "Visual Studio Community 2017",
    "description": "适用于学生、开放源代码和个体开发人员的免费、全功能型 IDE",
    "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
    "channelId": "VisualStudio.15.Release",
    "channelPath": "C:\\Users\\CharlieInc\\AppData\\Local\\Microsoft\\VisualStudio\\Packages\\_Channels\\4CB340F5\\catalog.json",
    "channelUri": "https://aka.ms/vs/15/release/channel",
    "releaseNotes": "https://go.microsoft.com/fwlink/?LinkId=660469#15.3.26730.12",
    "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660485"
  },
  {
    "instanceId": "75f3800a",
    "installDate": "2017-06-27T13:06:38Z",
    "installationName": "VisualStudioPreview/15.4.0-pre.1.0+26823.1",
    "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Preview\\Community",
    "installationVersion": "15.4.26823.1",
    "isPrerelease": true,
    "displayName": "Visual Studio Community 2017",
    "description": "适用于学生、开放源代码和个体开发人员的免费、全功能型 IDE",
    "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
    "channelId": "VisualStudio.15.Preview",
    "channelPath": "C:\\Users\\CharlieInc\\AppData\\Local\\Microsoft\\VisualStudio\\Packages\\_Channels\\48CDB76F\\catalog.json",
    "channelUri": "https://aka.ms/vs/15/pre/channel",
    "releaseNotes": "https://go.microsoft.com/fwlink/?LinkId=660693#15.4.26823.01",
    "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660708"
  },
  {
    "instanceId": "VisualStudio.14.0",
    "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\",
    "installationVersion": "14.0"
  }
]
```

**Comment by Bluesman74** [comment]
Json is
`[
  {
    "instanceId": "b7d2f31c",
    "installDate": "2017-07-13T07:54:58Z",
    "installationName": "VisualStudioPreview/15.4.0-pre.2.0+26906.1",
    "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Preview\\Enterprise",
    "installationVersion": "15.4.26906.1",
    "isPrerelease": true,
    "displayName": "Visual Studio Enterprise 2017",
    "description": "Microsoft DevOps solution for productivity and coordination across teams of any size",
    "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
    "channelId": "VisualStudio.15.Preview",
    "channelPath": "C:\\Users\\peter.nimmo\\AppData\\Local\\Microsoft\\VisualStudio\\Packages\\_Channels\\48CDB76F\\catalog.json",
    "channelUri": "https://aka.ms/vs/15/pre/channel",
    "releaseNotes": "https://go.microsoft.com/fwlink/?LinkId=660693#15.4.0-pre.2.0",
    "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660708"
  },
  {
    "instanceId": "VisualStudio.14.0",
    "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\",
    "installationVersion": "14.0"
  },
  {
    "instanceId": "VisualStudio.12.0",
    "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\",
    "installationVersion": "12.0"
  },
  {
    "instanceId": "VisualStudio.11.0",
    "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\",
    "installationVersion": "11.0"
  },
  {
    "instanceId": "VisualStudio.10.0",
    "installationPath": "c:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\",
    "installationVersion": "10.0"
  }
]`
Path is `C:\Cmder\bin;C:\Cmder\vendor\conemu-maximus5\ConEmu\Scripts;C:\Cmder\vendor\conemu-maximus5;C:\Cmder\vendor\conemu-maximus5\ConEmu;C:\Program Files\Microsoft MPI\Bin\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft Team Foundation Server 2015 Power Tools\;C:\Program Files\Git\cmd;C:\Users\me\.dnx\bin;C:\Users\me\AppData\Local\Microsoft\WindowsApps;C:\Users\me\AppData\Local\Microsoft\WindowsApps;C:\Users\me\AppData\Local\Continuum\Miniconda3\Scripts;C:\Cmder`

**Comment by fcharlie** [comment]
your clangbuilder env not init？

**Comment by Bluesman74** [comment]
Ah sorry you mean from your console?

`C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\VC\Tools\MSVC\14.11.25503\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.3;C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;C:\Program Files (x86)\HTML Help Workshop;C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Windows Kits\10\bin\10.0.15063.0\x64;C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\\MSBuild\15.0\bin;C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Common7\Tools\;C:\Users\me\Documents\VS2017\Libraries\clangbuilder\pkgs\vswhere;C:\Users\me\Documents\VS2017\Libraries\clangbuilder\pkgs\swigwin;C:\Users\me\Documents\VS2017\Libraries\clangbuilder\pkgs\Python;C:\Users\me\Documents\VS2017\Libraries\clangbuilder\pkgs\NuGet;C:\Users\me\Documents\VS2017\Libraries\clangbuilder\pkgs\NSIS;C:\Users\me\Documents\VS2017\Libraries\clangbuilder\pkgs\Ninja;C:\Users\me\Documents\VS2017\Libraries\clangbuilder\pkgs\MinGit\cmd;C:\Users\me\Documents\VS2017\Libraries\clangbuilder\pkgs\Gnuutils\bin;C:\Users\me\Documents\VS2017\Libraries\clangbuilder\pkgs\CMake\bin;C:\Users\me\Documents\VS2017\Libraries\clangbuilder\pkgs\7z;C:\WINDOWS;C:\WINDOWS\System32;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0`

**Comment by fcharlie** [comment]
OK i known, CMake current default use Release not Preview Visual Studio 2017, if you use it, suggest use `Ninja` Engine build clang.
