### ISSUE TITLE
Failed to create installation package

### ISSUE THREAD

**Issue by Bluesman74** [fstudio/clangbuilder#21]
Hi Charlie,

I now have it building successfully but the 'Create Installation Package' part failed.

Here is the tail end of the logging:

`  C:\clangbuilder\out\mainline\tools\lldb\tools\lldb-mi\MICmnLLDBDebuggerHandleEvents.cpp(265): warning C4062: enumerator 'lldb::eBreakpointEventTypeAutoContinueChanged' in switch of enum 'lldb::BreakpointEventType' is not handled [C:
\clangbuilder\out\msbuild\tools\lldb\tools\lldb-mi\lldb-mi.vcxproj]

    35 Warning(s)
    0 Error(s)

Time Elapsed 01:23:51.60
Build llvm completed, your can run cpack
CPack: Create package using NSIS
CPack: Install projects
CPack: - Install project: LLVM
CMake Error in C:/clangbuilder/out/msbuild/projects/compiler-rt/lib/cmake_install.cmake:
  File starts with a Byte-Order-Mark that is not UTF-8.
Call Stack (most recent call first):
  C:/clangbuilder/out/msbuild/projects/compiler-rt/cmake_install.cmake:33 (include)
  C:/clangbuilder/out/msbuild/projects/cmake_install.cmake:32 (include)
  C:/clangbuilder/out/msbuild/cmake_install.cmake:105 (include)

CMake Error at C:/clangbuilder/out/msbuild/projects/compiler-rt/cmake_install.cmake:33 (include):
  include could not find load file:

    C:/clangbuilder/out/msbuild/projects/compiler-rt/lib/cmake_install.cmake
Call Stack (most recent call first):
  C:/clangbuilder/out/msbuild/projects/cmake_install.cmake:32 (include)
  C:/clangbuilder/out/msbuild/cmake_install.cmake:105 (include)

Creating llvm-ranlib.exe
Creating llvm-lib.exe
Creating llvm-dlltool.exe
Creating clang++.exe
Creating clang-cl.exe
Creating clang-cpp.exe
Creating ../msbuild-bin/cl.exe
Creating lld-link.exe
Creating ld.lld.exe
Creating llvm-readelf.exe
CPack Error: Error when generating package: LLVM
compile llvm done, you can use it
PS C:\clangbuilder\out\msbuild>`

**Comment by fcharlie** [comment]
Your can update clangbuilder and retry or use Engine `Ninja`
