### ISSUE TITLE
Selectable Targets to build from UI?

### ISSUE THREAD

**Issue by oscarbg** [fstudio/clangbuilder#22]
as this can improve build speed greatly could be good to be able to select LLVM targets for example common "X86;NVPTX" for POCL CUDA support for example..

**Comment by fcharlie** [comment]
Good idea. Your can set cmakeflags.$Branch.json

**Comment by fcharlie** [comment]
@oscarbg The new **CMake custom flags** feature is helpful if you have, I will close this issue
