### ISSUE TITLE
Link error Hello World

### ISSUE THREAD

**Issue by Celes-Eternal** [fstudio/clangbuilder#25]
Hello,
I'm trying to bring LLVM tool chain (with libc++) to Window because my coworkers work on it and I'd like to be able to use some C++17, Boost Hana... That kind of thing.

I followed the readme, Trying to use VS Community 2017, x64, Release, Stable, Ninja Boostrap, Use Clean Environment, Link static runtime library, Build LLDB.

But after that I tried to compile a simple Hello world:
```
#include <iostream>

int main() {
	
	std::cout << "Hello World!" << std::endl;
	return 0;
}
```
And got link warnings: 

> PS D:\clangbuilder\out\bootstrap> .\bin\clang.exe .\test.cpp
> test-553061.o : warning LNK4217: locally defined symbol _CxxThrowException imported in function "class std::num_put<char,class std::ostreambuf_iterator<char,struct std::char_traits<char> > > const & __cdecl std::use_facet<class std::num_put<char,class std::ostreambuf_iterator<char,struct std::char_traits<char> > > >(class std::locale const &)" (??$use_facet@V?$num_put@DV?$ostreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@@std@@YAAEBV?$num_put@DV?$ostreambuf_iterator@DU?$char_traits@D@std@@@std@@@0@AEBVlocale@0@@Z)
> test-553061.o : warning LNK4217: locally defined symbol __std_terminate imported in function "int `public: __cdecl std::locale::~locale(void)'::`1'::dtor$6" (?dtor$6@?0???1locale@std@@QEAA@XZ@4HA)
> PS D:\clangbuilder\out\bootstrap>

I tried some things, like this one : https://llvm.org/docs/GettingStartedVS.html
But still link warnings.

And I don't even know how to link to libc++ x)

That's probably not into the scope of this project, but I think a documentation about the whole installation would be useful for dumb people like me :)

**Comment by fcharlie** [comment]
```powershell
clang++ -std=c++11 -stdlib=libc++ -nostdinc++ -Iinclude\c++\v1 -Llib hello.cc -lc++
## When add lib to env LIB
clang-cl -std:c++14  -Iinclude\c++\v1 hello.cc c++.lib
```

**Comment by Celes-Eternal** [comment]
Perfect :)
But I still think you should put this into the Readme.

I just need to configure Visual Studio now.
Thanks, you're a life safer !

**Comment by fcharlie** [comment]
@Celes-Eternal  ReadMe Update. and how to support C++17.

**Comment by Celes-Eternal** [comment]
Good job :)

**Comment by fcharlie** [comment]
see: https://reviews.llvm.org/D42354
