### ISSUE TITLE
Could you post a binary build of this tool?

### ISSUE THREAD

**Issue by NickStrupat** [fstudio/clangbuilder#26]
Hello :)

I'm having trouble on two different machines. I can't get `rc.exe` to work properly. The instructions did not work for me.

I'm wondering if you could release a build of this tool to the `releases` tab on github?

Thanks!

**Comment by fcharlie** [comment]
Sorry, build LLVM need rc.exe, see: https://github.com/llvm-mirror/llvm/blob/master/resources/windows_version_resource.rc .

**Comment by NickStrupat** [comment]
What if you released a build of your tool in which one of the form elements is a file path to `rc.exe`. I have `rc.exe`, but I can't get your `.bat`/`.ps1` scripts to find it.

**Comment by fcharlie** [comment]
You can update environment value `PATH`

cmd:

```cmd
SET PATH=/path/your/rc/dir;%PATH%
```
Or PowerShell:

```powershell
$env:PATH="/path/your/rc/dir;$($env:PATH)"
```

After run my script.

**Comment by NickStrupat** [comment]
If I have time, I will try to get this all working inside a docker container then put it on `The Docker Store`.

Found some info here to install the MS build tools in a Windows docker image:
https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container
