### ISSUE TITLE
Fully scripted way to build?

### ISSUE THREAD

**Issue by NickStrupat** [fstudio/clangbuilder#37]
I'm wondering if there is a fully scripted way to build `clang` without needing the UI?

**Comment by fcharlie** [comment]
You can use script not require clangbuilderui 

```cmd
%CLANGBUILDDIR%/bin/clangbuilder.bat 
```

```powershell
$CLANGBUILDDIR/bin/ClangbuilderTarget.ps1
```

Powershell Args:

```
param (
    [Parameter(Position = 0)]
    [Alias("id")]
    [String]$InstanceId, # install id
    [String]$InstallationVersion, # installationVersion
    [ValidateSet("x86", "x64", "ARM", "ARM64")]
    [String]$Arch = "x64",
    [ValidateSet("Release", "Debug", "MinSizeRel", "RelWithDebug")]
    [String]$Flavor = "Release",
    [ValidateSet("MSBuild", "Ninja", "NinjaBootstrap", "NinjaIterate")]
    [String]$Engine = "MSBuild",
    [ValidateSet("Mainline", "Stable", "Release")]
    [String]$Branch = "Mainline", #mainline 
    [Alias("e")]
    [Switch]$Environment, # start environment 
    [Switch]$Sdklow, # low sdk support
    [Switch]$LLDB,
    [Switch]$LTO,
    [Switch]$Package,
    [Switch]$ClearEnv
)
```
 If not set `InstanceId` and `InstallationVersion` clangbuilder will detect vs installation. Arch default is `x64` and Branch default is `Mainline` (git repository master branch).

Switch default is not set, `-Package` create install package. `-LLDB` will build lldb, `-LTO` build clang with lto (maybe failed) `-ClearEnv` will reset `PATH` 

`-Engine Name` will set Engine, or use msbuild or use ninja, or use prebuilt clang-cl as C/C++ compiler build llvm. or  bootstrap clang.

**Comment by fcharlie** [comment]
First. Your should run `script/InitializeEnv.bat` to install utils tools.

**Comment by NickStrupat** [comment]
I still have never had this work properly. I have the latest version of Visual Studio Community 2017 installed (15.7.4).

after running 
`.\script\InitializeEnv.bat`
I ran
`.\bin\ClangbuilderTarget.ps1 -InstanceId 8d9d99ef -InstallationVersion 15.7.27703.2035 -Branch Stable`

**Comment by fcharlie** [comment]
@NickStrupat Your console output is ?
