### ISSUE TITLE
ClangbuilderUI Add Windows 10 Theme support

### ISSUE THREAD

**Issue by fcharlie** [fstudio/clangbuilder#39]
Reference: 
[Allow for transparent / vibrant window theme](https://github.com/Microsoft/vscode/issues/32257)
[Windows 10 Fluent Design / Acrylic material](https://github.com/arkenthera/electron-vibrancy/issues/21)
[Adding the "Aero Glass" blur to your Windows 10 apps](https://withinrafael.com/2015/07/08/adding-the-aero-glass-blur-to-your-windows-10-apps/)
[https://github.com/arkenthera/electron-vibrancy/blob/master/src/vibrancy_win.cc](https://github.com/arkenthera/electron-vibrancy/blob/master/src/vibrancy_win.cc)

```c#
public enum AccentState
{
    ACCENT_DISABLED = 0,                    // Black and solid background
    ACCENT_ENABLE_GRADIENT = 1,             // Custom-colored solid background
    ACCENT_ENABLE_TRANSPARENTGRADIENT = 2,  // Custom-colored transparent background
    ACCENT_ENABLE_BLURBEHIND = 3,           // Custom-colored and blurred transparent background
    ACCENT_ENABLE_FLUENT = 4,               // Custom-colored Fluent effect
    ACCENT_INVALID_STATE = 5                // Completely transparent background
}

```

```c++
HWND hWnd = FindWindow("Chrome_WidgetWin_1", NULL);
ACCENTPOLICY policy = { 4, 2, 0xaa000000, 0 }; // ACCENT_ENABLE_FLUENT=4
WINCOMPATTRDATA data = { 19, &policy, sizeof(ACCENTPOLICY) }; // WCA_ACCENT_POLICY=19
SetWindowCompositionAttribute(hWnd, &data);
```

**Comment by DRSDavidSoft** [comment]
#52707.
