### ISSUE TITLE
compile error relatated json

### ISSUE THREAD

**Issue by princetonpku** [fstudio/clangbuilder#44]
When I use the json.hpp whose version is 3.7.0, there are some error in the following lines:
"auto j = nlohmann::json::parse(fd.P());", the function nlohmann::json::parse cannot process the return value of fd.P()

//sources\cli\cli.cc: 
auto file = bela::StringCat(root, L"\\config\\settings.json");
  clangbuilder::FD fd;
  if (_wfopen_s(&fd.fd, file.data(), L"rb") != 0) {
    return false;
  }
  try {
    auto j = nlohmann::json::parse(fd.P());

**Comment by fcharlie** [comment]
Can you provide more detailed error information, as well as the compiler environment. By the way, I am currently using Visual Studio 2019, so Visual Studio 2017 is not tested.

**Comment by princetonpku** [comment]
@fcharlie here are the information in the cmd
BTW，my  compiler environment is :VS2017  win10  64bit

E:\>cd E:\clangbuilder\script                                                                                           
E:\clangbuilder\script>InitializeEnv.bat
try download vswhere E:\clangbuilder\bin\pkgs\vswhere\vswhere.exe
Use Visual Studio 15.9.28307.812 x64
Update $env:VS150COMNTOOLS to: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\Tools\
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.9.15
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
Clangbuilder Utilities Environment
Copyright © 2019. Force Charlie. All Rights Reserved.

Building Clangbuilder Utils ...
C:\Program Files\CMake\bin\cmake.exe -G"NMake Makefiles" -DCMAKE_BUILD_TYPE=Release .. [E:\clangbuilder\sources\out]
-- The C compiler identification is MSVC 19.16.27032.1
-- The CXX compiler identification is MSVC 19.16.27032.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- IPO/LTO enabled
-- Configuring done
-- Generating done
-- Build files have been written to: E:/clangbuilder/sources/out
C:\Program Files\CMake\bin\cmake.exe --build .  --config Release [E:\clangbuilder\sources\out]
Scanning dependencies of target bela
[  2%] Building CXX object bela/src/bela/CMakeFiles/bela.dir/ascii.cc.obj
ascii.cc
[  5%] Building CXX object bela/src/bela/CMakeFiles/bela.dir/codecvt.cc.obj
codecvt.cc
[  7%] Building CXX object bela/src/bela/CMakeFiles/bela.dir/escaping.cc.obj
escaping.cc
[ 10%] Building CXX object bela/src/bela/CMakeFiles/bela.dir/fmt.cc.obj
fmt.cc
[ 12%] Building CXX object bela/src/bela/CMakeFiles/bela.dir/match.cc.obj
match.cc
[ 15%] Building CXX object bela/src/bela/CMakeFiles/bela.dir/memutil.cc.obj
memutil.cc
[ 17%] Building CXX object bela/src/bela/CMakeFiles/bela.dir/numbers.cc.obj
numbers.cc
[ 20%] Building CXX object bela/src/bela/CMakeFiles/bela.dir/stdwriter.cc.obj
stdwriter.cc
[ 23%] Building CXX object bela/src/bela/CMakeFiles/bela.dir/winansi.cc.obj
winansi.cc
[ 25%] Building CXX object bela/src/bela/CMakeFiles/bela.dir/str_split.cc.obj
str_split.cc
[ 28%] Building CXX object bela/src/bela/CMakeFiles/bela.dir/str_replace.cc.obj
str_replace.cc
[ 30%] Building CXX object bela/src/bela/CMakeFiles/bela.dir/strcat.cc.obj
strcat.cc
[ 33%] Building CXX object bela/src/bela/CMakeFiles/bela.dir/subsitute.cc.obj
subsitute.cc
[ 35%] Linking CXX static library ..\..\..\lib\bela.lib
[ 35%] Built target bela
Scanning dependencies of target belawin
[ 38%] Building CXX object bela/src/belawin/CMakeFiles/belawin.dir/env.cc.obj
env.cc
[ 41%] Building CXX object bela/src/belawin/CMakeFiles/belawin.dir/path.cc.obj
path.cc
[ 43%] Building CXX object bela/src/belawin/CMakeFiles/belawin.dir/realpath.cc.obj
realpath.cc
[ 46%] Building CXX object bela/src/belawin/CMakeFiles/belawin.dir/reparsepoint.cc.obj
reparsepoint.cc
[ 48%] Building CXX object bela/src/belawin/CMakeFiles/belawin.dir/appexeclink.cc.obj
appexeclink.cc
[ 51%] Building CXX object bela/src/belawin/CMakeFiles/belawin.dir/peimage.cc.obj
peimage.cc
[ 53%] Linking CXX static library ..\..\..\lib\belawin.lib
[ 53%] Built target belawin
Scanning dependencies of target belashl
[ 56%] Building CXX object bela/src/belashl/CMakeFiles/belashl.dir/picker.cc.obj
picker.cc
[ 58%] Linking CXX static library ..\..\..\lib\belashl.lib
[ 58%] Built target belashl
Scanning dependencies of target ClangbuilderUI
[ 61%] Building CXX object ui/CMakeFiles/ClangbuilderUI.dir/main.cc.obj
main.cc
[ 64%] Building CXX object ui/CMakeFiles/ClangbuilderUI.dir/appexec.cc.obj
appexec.cc
[ 66%] Building CXX object ui/CMakeFiles/ClangbuilderUI.dir/appui.cc.obj
appui.cc
[ 69%] Building CXX object ui/CMakeFiles/ClangbuilderUI.dir/settings.cc.obj
settings.cc
E:\clangbuilder\sources\.\include\json.hpp(20481): error C2416: attribute 'deprecated("Since 3.0.0")' cannot be applied in this context
E:\clangbuilder\sources\.\include\json.hpp(22424): note: see reference to class template instantiation 'nlohmann::basic_json<ObjectType,ArrayType,StringType,BooleanType,NumberIntegerType,NumberUnsignedType,NumberFloatType,AllocatorType,JSONSerializer>' being compiled
E:\clangbuilder\sources\.\include\json.hpp(20729): error C2416: attribute 'deprecated("Since 3.0.0")' cannot be applied in this context
NMAKE : fatal error U1077: 'C:\PROGRA~2\MICROS~1\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.

**Comment by fcharlie** [comment]
This seems to be a bug in a specific version of MSVC, my suggestion is to upgrade to Visual Studio 2019. see: https://github.com/nlohmann/json/issues/1675

**Comment by princetonpku** [comment]
@fcharlie Thank you for your quickly reply! I have change the json file and adjust the following code and make the compile successfully

**from:**
    auto j = nlohmann::json::parse(fd.P());
**change to:**
    std::ifstream steamFile(file, std::ios::in);
    auto j = nlohmann::json::parse(steamFile);
