### ISSUE TITLE
tar.exe: Error opening archive

### ISSUE THREAD

**Issue by misaka00251** [fstudio/clangbuilder#45]
![image](https://user-images.githubusercontent.com/3908746/65988481-8355d080-e4ba-11e9-853c-ec49fe89d169.png)

After downloading the release, it output this message. But the archive works just fine.

**Comment by fcharlie** [comment]
This is most likely due to the failure to download tar.gz to delete the file and redo this operation.

**Comment by misaka00251** [comment]
How to solve this? Every time when I need to build, I need to manually decompress it.

7zip said the downloaded archive has no error.

**Comment by fcharlie** [comment]
@misaka00251 You can use stable branch. In fact, stable branches may be a better choice than Release tags.

We use the Github archive to download the source code, which may fail. Example: https://github.com/llvm/llvm-project/archive/llvmorg-9.0.0.tar.gz

**Comment by fcharlie** [comment]
@misaka00251 I recently fixed the DPI scaling support for ClangbuilderUI, you can recompile clangbuilderUI.
